output_dir: ~/scratch/aaai24_outputs

dataset:
  class: PSRDataset
  path: ~/scratch/protein-datasets/
  atom_feature: null
  residue_feature: default
  transform:
    class: ProteinView
    view: residue

task:
  class: PropertyPrediction
  model:
    class: FusionNetwork
    sequence_model:
      class: ESM
      path: ~/scratch/protein-model-weights/esm-model-weights/
      model: ESM-2-650M
    structure_model:
      class: GearNet
      input_dim: 21
      hidden_dims: [512, 512, 512, 512, 512, 512]
      batch_norm: True
      concat_hidden: True
      short_cut: True
      readout: 'sum'
      num_relation: 7
    fusion: parallel
  graph_construction_model:
    class: GraphConstruction
    node_layers:
      - class: AlphaCarbonNode
    edge_layers:
      - class: SequentialEdge
        max_distance: 2
      - class: SpatialEdge
        radius: 10.0
        min_distance: 5
      - class: KNNEdge
        k: 10
        min_distance: 5
  criterion: mse
  num_mlp_layer: 3
  metric: ['mae', 'rmse', 'spearmanr']
  normalization: True
  num_class: 1

optimizer:
  class: Adam
  lr: 1.0e-4

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 2
  log_interval: 1000

metric: spearmanr [gdt_ts]
sequence_model_lr_ratio: 0.1

train:
  num_epoch: 20