output_dir: ~/scratch/aaai24_output

dataset:
  class: GeneOntology
  path: ~/scratch/protein-datasets/
  branch: {{ branch }}
  test_cutoff: 0.95
  atom_feature: null
  bond_feature: null
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: residue
      - class: TruncateProtein
        max_length: 550

task:
  class: MultipleBinaryClassification
  model:
    class: FusionNetwork
    sequence_model:
      class: ESM
      path: ~/scratch/protein-model-weights/esm-model-weights/
      model: ESM-2-650M
    structure_model:
      class: GearNet
      input_dim: 1280
      hidden_dims: [512, 512, 512, 512, 512, 512]
      batch_norm: True
      concat_hidden: True
      short_cut: True
      readout: 'sum'
      num_relation: 7
  graph_construction_model:
    class: GraphConstruction
    node_layers:
      - class: AlphaCarbonNode
    edge_layers:
      - class: SequentialEdge
        max_distance: 2
      - class: SpatialEdge
        radius: 10.0
        min_distance: 5
      - class: KNNEdge
        k: 10
        min_distance: 5
  criterion: bce
  num_mlp_layer: 3
  metric: ['auprc@micro', 'f1_max']

optimizer:
  class: Adam
  lr: 1.0e-4

scheduler:
  class: ReduceLROnPlateau
  factor: 0.6
  patience: 5

engine:
  gpus: [0, 1, 2, 3]
  batch_size: 2
  log_interval: 1000

# model_checkpoint: {{ ckpt }}

sequence_model_lr_ratio: 0.1

metric: f1_max

train:
  num_epoch: 50